

package alpona;


import java.awt.Color;
import java.awt.Cursor;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

public class CustomerProduct extends javax.swing.JFrame {

    ImageIcon ii;
     public static  String uname ;
    public void getString(String name){
        uname= name;
        //JOptionPane.showMessageDialog(null, uname);
    }
    public CustomerProduct() {
        
        initComponents();
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
               this.setLocationRelativeTo(null);
               dispose();
               setUndecorated(true);
               setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
               this.setVisible(true);
    }
      class jPanelGradient extends JPanel{
              protected void paintComponent(Graphics g){
                  Graphics2D g2d= (Graphics2D) g;
                  int width= getWidth();
                  int height= getHeight();
                  Color color1= new Color(171,102,255);
                  Color color2= new Color(116,182,247);
                  GradientPaint gp= new GradientPaint(0,0,color1,180,height,color2);
                  g2d.setPaint(gp);
                  g2d.fillRect(0,0,width, height);
              }
          }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        l16 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        l20 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        l22 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        l23 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        l5 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        l6 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new jPanelGradient();
        jLabel1 = new javax.swing.JLabel();
        Profile = new javax.swing.JButton();
        ChangeProfile = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jPanel2 = new jPanelGradient();
        l1 = new javax.swing.JLabel();
        ShellCraft = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LeatherCraft = new javax.swing.JButton();
        FiberCraft = new javax.swing.JButton();
        ClayCraft = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        MetalCraft = new javax.swing.JButton();
        WoodWork = new javax.swing.JButton();
        BambooandCane = new javax.swing.JButton();
        PaperCraft = new javax.swing.JButton();
        Sari = new javax.swing.JButton();
        Other = new javax.swing.JButton();
        Jute_Craft = new javax.swing.JButton();
        Nakshikantha = new javax.swing.JButton();

        jButton9.setBackground(new java.awt.Color(255, 204, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setText("Wood Work");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        l16.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        l17.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        l18.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        l4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        l19.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        jButton14.setBackground(new java.awt.Color(255, 204, 255));
        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton14.setText("Clay Craft");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 204, 255));
        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton15.setText("Wood Work");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 204, 255));
        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton16.setText("Shell Craft");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(255, 204, 255));
        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton17.setText("Stone Craft");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(255, 204, 255));
        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton18.setText("Sari and silk");
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(255, 204, 255));
        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton19.setText("Paper Craft");
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(255, 204, 255));
        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton20.setText("Bamboo and cane");
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(255, 204, 255));
        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton21.setText("Clay Craft");
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        l20.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        l21.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        jButton22.setBackground(new java.awt.Color(255, 204, 255));
        jButton22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton22.setText("Leather Crafts");
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        l22.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        jButton23.setBackground(new java.awt.Color(255, 204, 255));
        jButton23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton23.setText("Jute Craft");
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        l23.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        jButton24.setBackground(new java.awt.Color(255, 204, 255));
        jButton24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton24.setText("Nakshi Kantha");
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        l5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        jButton25.setBackground(new java.awt.Color(255, 204, 255));
        jButton25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton25.setText("Metal Craft");
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        l6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        l24.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\wood1.jpg")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Categories");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("products");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 650));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Alpona");

        Profile.setBackground(new java.awt.Color(153, 153, 153));
        Profile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Profile.setText("Profile");
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               ProfileActionPerformed(evt);
            }
        });

        ChangeProfile.setBackground(new java.awt.Color(153, 153, 153));
        ChangeProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChangeProfile.setText("Change Profile");
        ChangeProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeProfileActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(153, 153, 153));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChangeProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 545, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(Logout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Profile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangeProfile)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 650));

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("shell.jpg"))); // NOI18N

        ShellCraft.setBackground(new java.awt.Color(255, 204, 255));
        ShellCraft.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ShellCraft.setText("Shell Craft");
        ShellCraft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShellCraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShellCraftActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Categories");

        LeatherCraft.setBackground(new java.awt.Color(255, 204, 255));
        LeatherCraft.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LeatherCraft.setText("Leather Crafts");
        LeatherCraft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LeatherCraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeatherCraftActionPerformed(evt);
            }
        });

        FiberCraft.setBackground(new java.awt.Color(255, 204, 255));
        FiberCraft.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FiberCraft.setText("Fiber Craft");
        FiberCraft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FiberCraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiberCraftActionPerformed(evt);
            }
        });

        ClayCraft.setBackground(new java.awt.Color(255, 204, 255));
        ClayCraft.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ClayCraft.setText("Clay Craft");
        ClayCraft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClayCraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClayCraftActionPerformed(evt);
            }
        });

             
        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("metal.jpg"))); // NOI18N

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("wood1.jpg"))); // NOI18N

        l7.setIcon(new javax.swing.ImageIcon(getClass().getResource("bamboo.jpg"))); // NOI18N

        l8.setIcon(new javax.swing.ImageIcon(getClass().getResource("paper.jpg"))); // NOI18N

        l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("sari.jpg"))); // NOI18N

        l10.setIcon(new javax.swing.ImageIcon(getClass().getResource("nakshi.jpg"))); // NOI18N

        l11.setIcon(new javax.swing.ImageIcon(getClass().getResource("stone.jpg"))); // NOI18N

        l12.setIcon(new javax.swing.ImageIcon(getClass().getResource("clay craft.jpg"))); // NOI18N

        l13.setIcon(new javax.swing.ImageIcon(getClass().getResource("leather.jpg"))); // NOI18N

        l14.setIcon(new javax.swing.ImageIcon(getClass().getResource("fiber.png"))); // NOI18N

        l15.setIcon(new javax.swing.ImageIcon(getClass().getResource("jute.jpg"))); // NOI18N
         
         

        MetalCraft.setBackground(new java.awt.Color(255, 204, 255));
        MetalCraft.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MetalCraft.setText("Metal Craft");
        MetalCraft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MetalCraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetalCraftActionPerformed(evt);
            }
        });

        WoodWork.setBackground(new java.awt.Color(255, 204, 255));
        WoodWork.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WoodWork.setText("Wood Work");
        WoodWork.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WoodWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WoodWorkActionPerformed(evt);
            }
        });

        BambooandCane.setBackground(new java.awt.Color(255, 204, 255));
        BambooandCane.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BambooandCane.setText("Bamboo and cane");
        BambooandCane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BambooandCane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BambooandCaneActionPerformed(evt);
            }
        });

        PaperCraft.setBackground(new java.awt.Color(255, 204, 255));
        PaperCraft.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PaperCraft.setText("Paper Craft");
        PaperCraft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PaperCraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaperCraftActionPerformed(evt);
            }
        });

        Sari.setBackground(new java.awt.Color(255, 204, 255));
        Sari.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Sari.setText("Sari");
        Sari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SariActionPerformed(evt);
            }
        });

        Other.setBackground(new java.awt.Color(255, 204, 255));
        Other.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Other.setText("Other");
        Other.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherActionPerformed(evt);
            }
        });

        Jute_Craft.setBackground(new java.awt.Color(255, 204, 255));
        Jute_Craft.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jute_Craft.setText("Jute Craft");
        Jute_Craft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jute_Craft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jute_CraftActionPerformed(evt);
            }
        });

        Nakshikantha.setBackground(new java.awt.Color(255, 204, 255));
        Nakshikantha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Nakshikantha.setText("Nakshi Kantha");
        Nakshikantha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Nakshikantha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NakshikanthaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShellCraft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PaperCraft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(WoodWork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(l8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ClayCraft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MetalCraft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(l12))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Nakshikantha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(Jute_Craft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l7)
                            .addComponent(BambooandCane)
                            .addComponent(l11)
                            .addComponent(Other, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(l13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LeatherCraft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FiberCraft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(l12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ClayCraft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(WoodWork, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FiberCraft, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LeatherCraft, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(BambooandCane, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Other, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(MetalCraft, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Jute_Craft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Sari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nakshikantha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ShellCraft, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(PaperCraft, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
        private void l3MouseEntered(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
                ii= new ImageIcon(getClass().getResource("F:\\JavaSwing Project\\Alpona\\src\\alpona\\wood1.jpg"));
                l3.setIcon(ii);
           }  
         private void l3MouseExited(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
                ii= new ImageIcon(getClass().getResource("F:\\JavaSwing Project\\Alpona\\src\\alpona\\wood1Resize.jpg"));
                l3.setIcon(ii);
           }  
          private void l7MouseEntered(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        
           } 
    private void ShellCraftActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
              // TODO add your handling code here:
               dispose();
               product_list  ne = new product_list();
               ne.getString(ShellCraft.getText());
               ne.setVisible(true); 
    }                                          

    private void LeatherCraftActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
               dispose();
               product_list  ne = new product_list();
               ne.getString(LeatherCraft.getText());
               ne.setVisible(true); 
    }                                            

    private void FiberCraftActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
               dispose();
               product_list  ne = new product_list();
               ne.getString(FiberCraft.getText());
               ne.setVisible(true); 
    }                                          

    private void ClayCraftActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
               dispose();
               product_list  ne = new product_list();
               ne.getString(ClayCraft.getText());
               ne.setVisible(true); 
    }                                         

    private void MetalCraftActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
              dispose();
               product_list  ne = new product_list();
               ne.getString(MetalCraft.getText());
               ne.setVisible(true);      
    }                                          

    private void WoodWorkActionPerformed(java.awt.event.ActionEvent evt) {                                         
               dispose();
               product_list  ne = new product_list();
               ne.getString(WoodWork.getText());
               
               ne.setVisible(true); 
    }                                        

    private void BambooandCaneActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
          dispose();
               product_list  ne = new product_list();
               ne.getString(BambooandCane.getText());
               ne.setVisible(true); 
    }                                             

    private void PaperCraftActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
                dispose();
               product_list  ne = new product_list();
               ne.getString(PaperCraft.getText());
               ne.setVisible(true); 
                 
    }                                          

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void SariActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
              dispose();
               product_list  ne = new product_list();
               ne.getString(Sari.getText());
               ne.setVisible(true); 
    }                                    

    private void OtherActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
             dispose();
               product_list  ne = new product_list();
               ne.getString(Other.getText());
               ne.setVisible(true); 
    }                                     

    private void Jute_CraftActionPerformed(java.awt.event.ActionEvent evt) {                                           
          // TODO add your handling code here:
             dispose();
               product_list  ne = new product_list();
               ne.getString(Jute_Craft.getText());
               ne.setVisible(true); 
    }                                          

    private void NakshikanthaActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
               dispose();
               product_list  ne = new product_list();
               ne.getString(Nakshikantha.getText());
               ne.setVisible(true); 
    }                                            

    private void l1MouseEntered(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        
    }                                         
     private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        
    } 
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void ChangeProfileActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
              try {
            dispose();
            update_profile_c cp= new update_profile_c ();
            cp.tf6.setText(uname);
            String q= "select * from customer where CUsername='"+uname+"'";
            PreparedStatement p= connection.getConnection().prepareStatement(q);
            ResultSet rs= p.executeQuery(q);
            if(rs.next()){
                cp.tf1.setText(rs.getString("CFname"));
                cp.tf2.setText(rs.getString("CLname"));
                cp.tf4.setText(rs.getString("PhoneNo"));
                cp.tf5.setText(rs.getString("CEmail"));
                cp.ps.setText(rs.getString("Password"));
            }
            
            cp.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database related problem");
            Logger.getLogger(CustomerProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                             
    
      private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {
            dispose();
            LoginPage na = new LoginPage();
            na.setVisible(true);
      
      }
      
       private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {                                              
        try {
            dispose();
            cust_profile cp= new cust_profile();
            cp.tf6.setText(uname);
            String q= "select * from customer where CUsername='"+uname+"'";
            PreparedStatement p= connection.getConnection().prepareStatement(q);
            ResultSet rs= p.executeQuery(q);
            if(rs.next()){
                cp.tf1.setText(rs.getString("CFname"));
                cp.tf2.setText(rs.getString("CLname"));
                cp.tf4.setText(rs.getString("PhoneNo"));
                cp.tf5.setText(rs.getString("CEmail"));
            }
            
            cp.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database related problem");
            Logger.getLogger(CustomerProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
               
               
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BambooandCane;
    private javax.swing.JButton ChangeProfile;
    private javax.swing.JButton ClayCraft;
    private javax.swing.JButton FiberCraft;
    private javax.swing.JButton Jute_Craft;
    private javax.swing.JButton LeatherCraft;
    private javax.swing.JButton Logout;
    private javax.swing.JButton MetalCraft;
    private javax.swing.JButton Nakshikantha;
    private javax.swing.JButton Other;
    private javax.swing.JButton PaperCraft;
    private javax.swing.JButton Profile;
    private javax.swing.JButton Sari;
    private javax.swing.JButton ShellCraft;
    private javax.swing.JButton WoodWork;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l24;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration                   
}
